---
title: "SummarizedExperiment Sample"
author: "Maya Clapperton"
date: "2026-04-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Package install
```{r}
#install.packages("readxl")
library(readxl)
library(SummarizedExperiment)
#install.packages("shiny", dependencies = TRUE)
library(shiny)
```

Read in file
```{r}
df <- read_excel("C:/Users/mayac/OneDrive/Documents/VIDO/Transcriptome_Vilcheze.xlsx", sheet = "Table S2c log2 fold change")
```
Using just the acid transcriptome file to start


Now trying to manipulate the object
```{r}

#Extract assay matrix
assay_cols <- c(
  "log2 Fold change 1% O2",
  "log2 Fold change PBS",
  "log2 Fold change pH",
  "log2 Fold change Stationary phase")

assay_mat <- as.matrix(df[ , assay_cols])
rownames(assay_mat) <- df$Gene


#Build rowData
rowData <- DataFrame(
  gene_id   = df$Gene,
  gene_name = df$`Gene Name`,
  padj_1pctO2 = df$`padj 1% O2`,
  padj_PBS    = df$`padj PBS`,
  padj_pH     = df$`padj pH`,
  padj_StPh   = df$`padj StPh`)

rownames(rowData) <- df$Gene


#Build colData
colData <- DataFrame(
  condition = c("1% O2", "PBS", "pH", "Stationary phase"))

rownames(colData) <- assay_cols


#And now SummarizedExperiment
se <- SummarizedExperiment(
  assays = list(log2FC = assay_mat),
  rowData = rowData,
  colData = colData)

```


Okay let's investigate it
```{r}
se
rowData(se)[1:5, ]
colData(se)
assay(se, "log2FC")[1:5, ]

```

Investigating Making a Shiny app
```{r}
ui <- fluidPage(
  selectInput("dataset", label = "Dataset", choices = ls("package:datasets")),
  verbatimTextOutput("summary"),
  tableOutput("table")
)

server <- function(input, output, session) {
  # Create a reactive expression
  dataset <- reactive({
    get(input$dataset, "package:datasets")
  })

  output$summary <- renderPrint({
    # Use a reactive expression by calling it like a function
    summary(dataset())
  })
  
  output$table <- renderTable({
    dataset()
  })
}

shinyApp(ui, server)
```



